# Generated by Django 5.1.4 on 2024-12-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_coinwallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
