# Generated by Django 5.1.4 on 2024-12-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, default='/images/no-img.png', null=True, upload_to='images/doctor_avatar/'),
        ),
    ]
