# Generated by Django 5.1.4 on 2024-12-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shippingcharge_cart_shipping_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_charge',
        ),
    ]
