# Generated by Django 5.1.4 on 2024-12-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_shippingaddress_inside_dhaka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_charge',
        ),
        migrations.AddField(
            model_name='order',
            name='inside_dhaka',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zip_code',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
