# Generated by Django 5.1.4 on 2024-12-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
