# Generated by Django 5.1.4 on 2024-12-27 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_cart_user_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.shippingaddress'),
        ),
    ]
