# Generated by Django 5.1.4 on 2024-12-27 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_coupon_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='coupon_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
